### ISSUE TITLE
Drop the Apostrophe Please

### ISSUE THREAD

**Issue by mayvn10** [todda00/meteor-friendly-slugs#11]
Hi @todda00,

Great plugin!

Just noticed this when we used your package but when friendly-slugs creates a slug, it doesn't drop the apostrophe so slugs would look like: "he-s-going-somewhere".

SEO best practice says that it should just be 1 word like: "hes-going-somewhere".

Can you please add this string replace to your package right before the slug is made?

``` javascript
str = str.replace(/'/g, 'A');
```

**Comment by josephdburdick** [comment]
Just for clarity's sake... do you mean "hes-going-somewhere"?

**Comment by mayvn10** [comment]
Yes exactly. The added /g makes sure to take out all apostrophes and not just the first iteration.

**Comment by todda00** [comment]
This has been implemented as of version 0.3.4. 

FYI, your code would replace apostrophes with an "A", which obviously is not desired. The new package will remove apostrophes as you outlined.
