### ISSUE TITLE
Error: Match error: Expected Number in field maxLength

### ISSUE THREAD

**Issue by dyaa** [todda00/meteor-friendly-slugs#22]
While using the Meteor package Spiderable and rendering a page like a robot let's say

```
curl http://localhost:3000/blog?_escaped_fragment_=
```

I got this error 

Error: Match error: Expected Number in field maxLength 

Which leads us to #19 any idea what's going ?

My Setup is 

```
Collection.friendlySlugs(
    {
        slugFrom: 'title',
        slugField: 'slug',
        maxLength: 0
    }
);
```

**Comment by todda00** [comment]
You don't get this error when browsing the page normally, without the _escaped_fragment ?

Does the error remain if you do not include maxLength in your options (defaults to 0)?

Also please try with a number greater than 0 and let me know if the error remains.

**Comment by dyaa** [comment]
You don't get this error when browsing the page normally, without the _escaped_fragment ? **YES**

Does the error remain if you do not include maxLength in your options (defaults to 0)? **YES**

Also please try with a number greater than 0 and let me know if the error remains.

**Tried now with the same issue.**

**Comment by dyaa** [comment]
@todda00 Any Updates!

**Comment by dyaa** [comment]
@todda00 Any Updates!

**Comment by dyaa** [comment]
Hello @todda00 Any Updates!

**Comment by dyaa** [comment]
Here's the full error

```

Error: Match error: Expected Number in field maxLength

  http://localhost:3000/packages/check.js?9c4972d3f4fe56cd455d3022e70b5195e642fc41:66
  http://localhost:3000/packages/todda00_friendly-slugs.js?fef7eb9e720fff955e69c5880a285907ca768591:171
  http://localhost:3000/packages/es5-shim.js?03b82f907286b5353e3a371eb320635a634fc88b:517 in forEach
  http://localhost:3000/packages/underscore.js?46eaedbdeb6e71c82af1b16f51c7da4127d6f285:149
  http://localhost:3000/packages/todda00_friendly-slugs.js?fef7eb9e720fff955e69c5880a285907ca768591:229
  http://localhost:3000/app/model/articles.js?f812225629eeec0ef62eb96b50d54983c3ef6df0:7
  http://localhost:3000/app/model/articles.js?f812225629eeec0ef62eb96b50d54983c3ef6df0:95
```

**Comment by dyaa** [comment]
Reverted back to `0.3.4`

**Comment by todda00** [comment]
Can you pull https://github.com/todda00/meteor-friendly-slugs/tree/issue-22 in as a local package and see if it fixes your issue?
