### ISSUE TITLE
Friendly Slugs for Foreign/Special Characters

### ISSUE THREAD

**Issue by mayvn10** [todda00/meteor-friendly-slugs#26]
The friendly slugs package for Meteor seems like it only supports English characters.

Is there a good/efficient approach to creating slugs for foreign (or special) characters in Chinese, Japanese, etc?

Thanks in advance.

**Comment by mayvn10** [comment]
Any possible solutions here? How can we add support for foreign characters?

**Comment by todda00** [comment]
You can add your own transliteration set by adding a transliteration array in the options. You can convert any number of characters to whatever characters you would like. If you would like to provide some suggested transliterations to include in the defaults, please do so and they will be added if they make sense.
