### ISSUE TITLE
Error: Not permitted.

### ISSUE THREAD

**Issue by Tim-W** [todda00/meteor-friendly-slugs#27]
`Topics.update(
                    {slug: topicSlug},
                    {
                        $addToSet: {
                            posts: result
                        }
                    });
`

When I try to update a document using the slug attribute instead of _id, I get the following error:
"Error: Not permitted. Untrusted code may only update documents by ID. [403]"

I understand why this error gets thrown, but what is the preferred workaround to update a single document selected by slug instead of _id?

**Comment by todda00** [comment]
This is a restriction from Meteor, not this package. You can handle this one of two ways:
1. Make sure the _id is available in whatever context you need to update the record and use that as the selector.
2. Use a method to complete the update.
