### ISSUE TITLE
Failing on Meteor 2.3+

### ISSUE THREAD

**Issue by iancwinter** [todda00/meteor-friendly-slugs#35]
I’m getting this response when trying to add the package to Meteor 2.3.1:

```
meteor add todda00:friendly-slugs
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint accounts-base@1.2.0 is not satisfied by accounts-base 2.0.0.
Constraints on package "accounts-base":
* accounts-base@~2.0.0 <- top level
* accounts-base@2.0.0 <- accounts-ui 1.4.0
* accounts-base@2.0.0 <- service-configuration 1.1.0 <- accounts-base 2.0.0 <- accounts-password 2.0.0
* accounts-base@2.0.0 <- accounts-ui-unstyled 1.5.0 <- accounts-ui 1.4.0
* accounts-base@2.0.0 <- accounts-password 2.0.0
* accounts-base@1.2.0 <- matb33:collection-hooks 0.7.15 <- todda00:friendly-slugs 0.6.0
```

Taking a guess – this may be because https://atmospherejs.com/matb33/collection-hooks was updated in June?

**Comment by w4pnemsak** [comment]
Same here, any chance this is handled in near future?

**Comment by tosinek** [comment]
If you don't know how to fix this yourself: 

- Clone this package to your repo into a folder named `packages` (by default)
- Update `package.js` and set its version constraint to eg `'matb33:collection-hooks@1.1.1-1'` (from `'matb33:collection-hooks@0.7.6'`)

**Comment by guncebektas** [comment]
the package became compatible with 2.8.1. closing
