### ISSUE TITLE
Mongo error when using $inc operator

### ISSUE THREAD

**Issue by alexcavender** [todda00/meteor-friendly-slugs#5]
First, thank you for making this package it's really amazing.
I have a Meteor method increasePlayCount

 increasePlayCount: function (DownloadId){
     Downloads.update({slug:DownloadId}, {$inc: {plays:1 }});
  },

Using $inc to increase a field in mongo gives me this error: 

![screen shot 2015-05-30 at 6 54 00 pm](https://cloud.githubusercontent.com/assets/5915265/7899721/49e03498-06fd-11e5-86c7-d3e0806a3bb2.png)

Using $set works normally on my collections

If I remove my code that calls friendly slugs then I can use $inc with no errors
Collection.friendlySlugs('name');

**Comment by todda00** [comment]
This should be fixed in 0.3.1, please update to the latest!
