### ISSUE TITLE
Doesn't work. Doesn't form the filed named slug.

### ISSUE THREAD

**Issue by abhisheksoni27** [todda00/meteor-friendly-slugs#8]

**Comment by todda00** [comment]
I am going to need some more information, can you paste in your collection definition and where you are defining the friendlySlugs for the collection?

**Comment by bjarketrux** [comment]
Existing documents are not updated automatically.
Try resetting your DB `meteor reset` (in development) or update the existing documents:
https://github.com/todda00/meteor-friendly-slugs#creating-slugs-in-bulk-for-existing-documents

**Comment by todda00** [comment]
Closing this issue, feel free to comment with additional information if you would like to re-open it.
